export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  category: "electronics" | "apparel" | "home" | "books" | "outdoor";
  rating: number;
  reviewsCount: number;
  stock: number;
  imageUrl: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "prod-01",
    name: "Aceso Wireless Noise-Canceling Headphones",
    slug: "wireless-noise-canceling-headphones",
    description: "Premium over-ear wireless headphones with active noise cancellation and 40-hour battery life.",
    price: 199.99,
    category: "electronics",
    rating: 4.8,
    reviewsCount: 142,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
  },
  {
    id: "prod-02",
    name: "Ultra-Slim Ergonomic Mechanical Keyboard",
    slug: "ergonomic-mechanical-keyboard",
    description: "Compact mechanical keyboard with hot-swappable switches, RGB backlighting, and low-latency Bluetooth.",
    price: 129.50,
    category: "electronics",
    rating: 4.7,
    reviewsCount: 98,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80",
  },
  {
    id: "prod-03",
    name: "Precision Wireless Optical Mouse",
    slug: "precision-wireless-optical-mouse",
    description: "Lightweight wireless gaming and productivity mouse with 26,000 DPI optical sensor.",
    price: 69.99,
    category: "electronics",
    rating: 4.6,
    reviewsCount: 76,
    stock: 40,
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
  },
  {
    id: "prod-04",
    name: "4K Portable IPS Monitor (15.6 Inch)",
    slug: "portable-ips-monitor-15-inch",
    description: "USB-C plug-and-play portable monitor with 100% sRGB color gamut and dual stereo speakers.",
    price: 249.00,
    category: "electronics",
    rating: 4.5,
    reviewsCount: 52,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80",
  },
  {
    id: "prod-05",
    name: "Smart Fitness Activity Tracker Watch",
    slug: "smart-fitness-activity-tracker-watch",
    description: "Waterproof smartwatch with continuous heart-rate monitoring, SpO2 sensor, and sleep tracking.",
    price: 89.99,
    category: "electronics",
    rating: 4.3,
    reviewsCount: 110,
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
  },
  {
    id: "prod-06",
    name: "Heavyweight Cotton Minimalist Hoodie",
    slug: "heavyweight-cotton-minimalist-hoodie",
    description: "100% organic combed cotton unisex hoodie designed for all-day comfort and warmth.",
    price: 74.00,
    category: "apparel",
    rating: 4.9,
    reviewsCount: 88,
    stock: 50,
    imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80",
  },
  {
    id: "prod-07",
    name: "Tailored Oxford Button-Down Shirt",
    slug: "tailored-oxford-button-down-shirt",
    description: "Classic wrinkle-resistant cotton Oxford shirt suitable for casual and business settings.",
    price: 58.00,
    category: "apparel",
    rating: 4.6,
    reviewsCount: 64,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80",
  },
  {
    id: "prod-08",
    name: "Performance Breathable Running Shoes",
    slug: "performance-breathable-running-shoes",
    description: "Cushioned road running shoes with responsive foam midsole and engineered mesh upper.",
    price: 119.99,
    category: "apparel",
    rating: 4.7,
    reviewsCount: 120,
    stock: 22,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
  },
  {
    id: "prod-09",
    name: "All-Weather Technical Windbreaker Jacket",
    slug: "technical-windbreaker-jacket",
    description: "Lightweight packable shell jacket with DWR water-repellent coating and sealed seams.",
    price: 95.00,
    category: "apparel",
    rating: 4.5,
    reviewsCount: 45,
    stock: 19,
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=600&q=80",
  },
  {
    id: "prod-10",
    name: "Merino Wool Everyday Crew Socks (3-Pack)",
    slug: "merino-wool-everyday-crew-socks",
    description: "Temperature-regulating, naturally odor-resistant merino wool socks reinforced at heel and toe.",
    price: 28.00,
    category: "apparel",
    rating: 4.8,
    reviewsCount: 73,
    stock: 60,
    imageUrl: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&q=80",
  },
  {
    id: "prod-11",
    name: "Artisan Ceramic Pour-Over Coffee Dripper",
    slug: "ceramic-pour-over-coffee-dripper",
    description: "Handcrafted ceramic cone dripper engineered for consistent heat retention and extraction.",
    price: 34.50,
    category: "home",
    rating: 4.9,
    reviewsCount: 84,
    stock: 28,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80",
  },
  {
    id: "prod-12",
    name: "Stainless Steel Gooseneck Electric Kettle",
    slug: "stainless-steel-gooseneck-electric-kettle",
    description: "Variable temperature control electric kettle with precise 1-degree adjustments and hold mode.",
    price: 89.00,
    category: "home",
    rating: 4.8,
    reviewsCount: 112,
    stock: 16,
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80",
  },
  {
    id: "prod-13",
    name: "Dimmable Architectural Desk Lamp",
    slug: "dimmable-architectural-desk-lamp",
    description: "Modern aluminum task lamp with adjustable color temperature, memory function, and clamp mount.",
    price: 64.99,
    category: "home",
    rating: 4.7,
    reviewsCount: 61,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
  },
  {
    id: "prod-14",
    name: "Organic Bamboo Cutting Board with Juice Groove",
    slug: "organic-bamboo-cutting-board",
    description: "Extra-thick sustainable bamboo butcher block with non-slip silicone feet.",
    price: 38.00,
    category: "home",
    rating: 4.6,
    reviewsCount: 95,
    stock: 44,
    imageUrl: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&q=80",
  },
  {
    id: "prod-15",
    name: "Aroma Diffuser with Ambient LED Lighting",
    slug: "aroma-diffuser-ambient-lighting",
    description: "Ultrasonic cool-mist essential oil diffuser featuring whisper-quiet 20dB operation.",
    price: 42.00,
    category: "home",
    rating: 4.4,
    reviewsCount: 78,
    stock: 32,
    imageUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80",
  },
  {
    id: "prod-16",
    name: "Designing Data-Intensive Applications",
    slug: "designing-data-intensive-applications",
    description: "The definitive guide to the architecture, reliability, and scalability of modern data systems.",
    price: 46.99,
    category: "books",
    rating: 5.0,
    reviewsCount: 310,
    stock: 45,
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80",
  },
  {
    id: "prod-17",
    name: "Site Reliability Engineering: How Google Runs Production",
    slug: "site-reliability-engineering-book",
    description: "Foundational essays and architectural case studies on building scalable, reliable distributed systems.",
    price: 42.50,
    category: "books",
    rating: 4.9,
    reviewsCount: 220,
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3777f?w=600&q=80",
  },
  {
    id: "prod-18",
    name: "Building Microservices: Designing Fine-Grained Systems",
    slug: "building-microservices-book",
    description: "Comprehensive guide to microservice architectures, service decomposition, and testing strategies.",
    price: 49.00,
    category: "books",
    rating: 4.7,
    reviewsCount: 140,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&q=80",
  },
  {
    id: "prod-19",
    name: "Refactoring: Improving the Design of Existing Code",
    slug: "refactoring-martin-fowler-book",
    description: "Classic guide to improving code health, testability, and maintainability without changing behavior.",
    price: 52.00,
    category: "books",
    rating: 4.8,
    reviewsCount: 185,
    stock: 28,
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80",
  },
  {
    id: "prod-20",
    name: "The Pragmatic Programmer: 20th Anniversary Edition",
    slug: "the-pragmatic-programmer-book",
    description: "Timeless advice for software developers on craftsmanship, career growth, and code quality.",
    price: 45.00,
    category: "books",
    rating: 4.9,
    reviewsCount: 265,
    stock: 33,
    imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&q=80",
  },
  {
    id: "prod-21",
    name: "Ultralight 2-Person Backpacking Tent",
    slug: "ultralight-backpacking-tent-2-person",
    description: "Three-season freestanding tent weighing under 2.8 lbs with silnylon rainfly and aluminum poles.",
    price: 279.99,
    category: "outdoor",
    rating: 4.8,
    reviewsCount: 67,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80",
  },
  {
    id: "prod-22",
    name: "Vacuum Insulated Stainless Steel Bottle (32oz)",
    slug: "vacuum-insulated-stainless-bottle-32oz",
    description: "Double-wall insulated bottle keeping beverages cold for 24 hours or hot for 12 hours.",
    price: 32.00,
    category: "outdoor",
    rating: 4.9,
    reviewsCount: 154,
    stock: 75,
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
  },
  {
    id: "prod-23",
    name: "Waterproof 45L Expedition Trail Backpack",
    slug: "waterproof-expedition-trail-backpack",
    description: "Ergonomic internal-frame backpack with adjustable torso length and integrated rain cover.",
    price: 155.00,
    category: "outdoor",
    rating: 4.7,
    reviewsCount: 89,
    stock: 14,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
  },
  {
    id: "prod-24",
    name: "Rechargeable 1000 Lumen LED Headlamp",
    slug: "rechargeable-1000-lumen-led-headlamp",
    description: "IPX6 waterproof headlamp with red light night-vision mode, motion sensor switch, and USB-C.",
    price: 39.99,
    category: "outdoor",
    rating: 4.6,
    reviewsCount: 102,
    stock: 38,
    imageUrl: "https://images.unsplash.com/photo-1517824806704-9040b037703b?w=600&q=80",
  },
  {
    id: "prod-25",
    name: "Titanium Ultralight Camp Cooking Set",
    slug: "titanium-ultralight-camp-cooking-set",
    description: "Corrosion-resistant 750ml titanium pot with lid and folding handles, nestable with 100g fuel canisters.",
    price: 49.50,
    category: "outdoor",
    rating: 4.8,
    reviewsCount: 71,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&q=80",
  },
  {
    id: "prod-26",
    name: "Fast-Charging 65W GaN Compact Charger",
    slug: "fast-charging-65w-gan-compact-charger",
    description: "Pocket-sized GaN power adapter with dual USB-C and USB-A ports for laptops, tablets, and phones.",
    price: 36.99,
    category: "electronics",
    rating: 4.8,
    reviewsCount: 133,
    stock: 45,
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&q=80",
  },
  {
    id: "prod-27",
    name: "100W Braided USB-C to USB-C Cable (2m)",
    slug: "braided-usbc-cable-2m",
    description: "Reinforced nylon braided cable supporting 100W Power Delivery and 480Mbps data transfer.",
    price: 14.99,
    category: "electronics",
    rating: 4.7,
    reviewsCount: 204,
    stock: 90,
    imageUrl: "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&q=80",
  },
  {
    id: "prod-28",
    name: "Heavy-Duty Canvas Weekender Duffle Bag",
    slug: "canvas-weekender-duffle-bag",
    description: "Waxed cotton canvas travel bag with genuine leather straps and dedicated shoe compartment.",
    price: 110.00,
    category: "apparel",
    rating: 4.6,
    reviewsCount: 56,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
  },
  {
    id: "prod-29",
    name: "Cast Iron Pre-Seasoned Skillet (10 Inch)",
    slug: "cast-iron-pre-seasoned-skillet",
    description: "Versatile heavy-duty cast iron skillet with superior heat retention for stove, oven, or campfire.",
    price: 32.50,
    category: "home",
    rating: 4.9,
    reviewsCount: 215,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1584990347449-399a9b9a66ba?w=600&q=80",
  },
  {
    id: "prod-30",
    name: "Insulated Down Camping Blanket",
    slug: "insulated-down-camping-blanket",
    description: "Packable water-resistant 650-fill duck down blanket with snap clasps to wear as a hands-free poncho.",
    price: 88.00,
    category: "outdoor",
    rating: 4.7,
    reviewsCount: 62,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=600&q=80",
  },
];

export function getProducts(query?: string, category?: string): Product[] {
  let filtered = [...PRODUCTS];

  if (category && category !== "all") {
    filtered = filtered.filter((p) => p.category === category);
  }

  if (query && query.trim() !== "") {
    const q = query.toLowerCase().trim();
    filtered = filtered.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.description.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q)
    );
  }

  return filtered;
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
